# Install with "conda env create -f environment.yml"
# Environment name can be overwritten via -n env_name
name: aurorabp
channels:
  - defaults
platforms:
  - linux-64
  - win-64
  - osx-64
  - osx-arm64
dependencies:
  - python=3.8
  - matplotlib
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - seaborn
  - notebook
